/*
 * This file is auto-generated. Modifications will be lost.
 *
 * See https://android.googlesource.com/platform/bionic/+/master/libc/kernel/
 * for more information.
 */
#ifndef __V4l2_VIDC_EXTENSIONS_H__
#define __V4l2_VIDC_EXTENSIONS_H__
#include <linux/types.h>
#include <linux/v4l2-controls.h>
#ifndef V4L2_PIX_FMT_AV1
#define V4L2_PIX_FMT_AV1 v4l2_fourcc('A', 'V', '1', '0')
#endif
#define V4L2_PIX_FMT_VIDC_HEIC v4l2_fourcc('H', 'E', 'I', 'C')
#define V4L2_META_FMT_VIDC v4l2_fourcc('Q', 'M', 'E', 'T')
#ifndef V4L2_MPEG_VIDEO_HEVC_PROFILE_MAIN_10_STILL_PICTURE
#define V4L2_MPEG_VIDEO_HEVC_PROFILE_MAIN_10_STILL_PICTURE (3)
#endif
#ifndef V4L2_MPEG_VIDEO_HEVC_PROFILE_MAIN_MULTIVIEW
#define V4L2_MPEG_VIDEO_HEVC_PROFILE_MAIN_MULTIVIEW (4)
#endif
#ifndef V4L2_MPEG_VIDEO_HEVC_PROFILE_MAIN_10_MULTIVIEW
#define V4L2_MPEG_VIDEO_HEVC_PROFILE_MAIN_10_MULTIVIEW (5)
#endif
#ifdef V4L2_CTRL_CLASS_CODEC
#define V4L2_CID_MPEG_VIDC_BASE (V4L2_CTRL_CLASS_CODEC | 0x2000)
#else
#define V4L2_CID_MPEG_VIDC_BASE (V4L2_CTRL_CLASS_MPEG | 0x2000)
#endif
#define V4L2_MPEG_MSM_VIDC_DISABLE 0
#define V4L2_MPEG_MSM_VIDC_ENABLE 1
#define V4L2_CID_MPEG_VIDC_SECURE (V4L2_CID_MPEG_VIDC_BASE + 0x1)
#define V4L2_CID_MPEG_VIDC_LOWLATENCY_REQUEST (V4L2_CID_MPEG_VIDC_BASE + 0x3)
#define V4L2_CID_MPEG_VIDC_CODEC_CONFIG (V4L2_CID_MPEG_VIDC_BASE + 0x4)
#define V4L2_CID_MPEG_VIDC_FRAME_RATE (V4L2_CID_MPEG_VIDC_BASE + 0x5)
#define V4L2_CID_MPEG_VIDC_OPERATING_RATE (V4L2_CID_MPEG_VIDC_BASE + 0x6)
#define V4L2_CID_MPEG_VIDC_TIME_DELTA_BASED_RC (V4L2_CID_MPEG_VIDC_BASE + 0xD)
#define V4L2_CID_MPEG_VIDC_CONTENT_ADAPTIVE_CODING (V4L2_CID_MPEG_VIDC_BASE + 0xE)
#define V4L2_CID_MPEG_VIDC_QUALITY_BITRATE_BOOST (V4L2_CID_MPEG_VIDC_BASE + 0xF)
#define V4L2_CID_MPEG_VIDC_BLUR_TYPES (V4L2_CID_MPEG_VIDC_BASE + 0x10)
enum v4l2_mpeg_vidc_blur_types {
  VIDC_BLUR_NONE = 0x0,
  VIDC_BLUR_EXTERNAL = 0x1,
  VIDC_BLUR_ADAPTIVE = 0x2,
};
#define V4L2_CID_MPEG_VIDC_BLUR_RESOLUTION (V4L2_CID_MPEG_VIDC_BASE + 0x11)
#define V4L2_CID_MPEG_VIDC_CSC_CUSTOM_MATRIX (V4L2_CID_MPEG_VIDC_BASE + 0x12)
#define V4L2_CID_MPEG_VIDC_METADATA_LTR_MARK_USE_DETAILS (V4L2_CID_MPEG_VIDC_BASE + 0x13)
#define V4L2_CID_MPEG_VIDC_METADATA_SEQ_HEADER_NAL (V4L2_CID_MPEG_VIDC_BASE + 0x14)
#define V4L2_CID_MPEG_VIDC_METADATA_DPB_LUMA_CHROMA_MISR (V4L2_CID_MPEG_VIDC_BASE + 0x15)
#define V4L2_CID_MPEG_VIDC_METADATA_OPB_LUMA_CHROMA_MISR (V4L2_CID_MPEG_VIDC_BASE + 0x16)
#define V4L2_CID_MPEG_VIDC_METADATA_INTERLACE (V4L2_CID_MPEG_VIDC_BASE + 0x17)
#define V4L2_CID_MPEG_VIDC_METADATA_CONCEALED_MB_COUNT (V4L2_CID_MPEG_VIDC_BASE + 0x18)
#define V4L2_CID_MPEG_VIDC_METADATA_HISTOGRAM_INFO (V4L2_CID_MPEG_VIDC_BASE + 0x19)
#define V4L2_CID_MPEG_VIDC_METADATA_SEI_MDCV (V4L2_CID_MPEG_VIDC_BASE + 0x1A)
#define V4L2_CID_MPEG_VIDC_METADATA_SEI_CLL (V4L2_CID_MPEG_VIDC_BASE + 0x1B)
#define V4L2_CID_MPEG_VIDC_METADATA_HDR10PLUS (V4L2_CID_MPEG_VIDC_BASE + 0x1C)
#define V4L2_CID_MPEG_VIDC_METADATA_EVA_STATS (V4L2_CID_MPEG_VIDC_BASE + 0x1D)
#define V4L2_CID_MPEG_VIDC_METADATA_BUFFER_TAG (V4L2_CID_MPEG_VIDC_BASE + 0x1E)
#define V4L2_CID_MPEG_VIDC_METADATA_SUBFRAME_OUTPUT (V4L2_CID_MPEG_VIDC_BASE + 0x1F)
#define V4L2_CID_MPEG_VIDC_METADATA_ROI_INFO (V4L2_CID_MPEG_VIDC_BASE + 0x20)
#define V4L2_CID_MPEG_VIDC_METADATA_TIMESTAMP (V4L2_CID_MPEG_VIDC_BASE + 0x21)
#define V4L2_CID_MPEG_VIDC_METADATA_ENC_QP_METADATA (V4L2_CID_MPEG_VIDC_BASE + 0x22)
#define V4L2_CID_MPEG_VIDC_MIN_BITSTREAM_SIZE_OVERWRITE (V4L2_CID_MPEG_VIDC_BASE + 0x23)
#define V4L2_CID_MPEG_VIDC_METADATA_BITSTREAM_RESOLUTION (V4L2_CID_MPEG_VIDC_BASE + 0x24)
#define V4L2_CID_MPEG_VIDC_METADATA_CROP_OFFSETS (V4L2_CID_MPEG_VIDC_BASE + 0x25)
#define V4L2_CID_MPEG_VIDC_METADATA_SALIENCY_INFO (V4L2_CID_MPEG_VIDC_BASE + 0x26)
#define V4L2_CID_MPEG_VIDC_METADATA_TRANSCODE_STAT_INFO (V4L2_CID_MPEG_VIDC_BASE + 0x27)
#define V4L2_CID_MPEG_VIDC_SUPERFRAME (V4L2_CID_MPEG_VIDC_BASE + 0x28)
#define V4L2_CID_MPEG_VIDC_THUMBNAIL_MODE (V4L2_CID_MPEG_VIDC_BASE + 0x29)
#define V4L2_CID_MPEG_VIDC_PRIORITY (V4L2_CID_MPEG_VIDC_BASE + 0x2A)
#define V4L2_CID_MPEG_VIDC_METADATA_DPB_TAG_LIST (V4L2_CID_MPEG_VIDC_BASE + 0x2B)
#define V4L2_CID_MPEG_VIDC_COMPRESSION_RATIO (V4L2_CID_MPEG_VIDC_BASE + 0x2C)
#define V4L2_CID_MPEG_VIDC_METADATA_QP (V4L2_CID_MPEG_VIDC_BASE + 0x2E)
#define V4L2_CID_MPEG_VIDC_COMPLEXITY (V4L2_CID_MPEG_VIDC_BASE + 0x2F)
#define V4L2_CID_MPEG_VIDC_METADATA_MAX_NUM_REORDER_FRAMES (V4L2_CID_MPEG_VIDC_BASE + 0x30)
#define V4L2_CID_MPEG_VIDC_AV1_PROFILE (V4L2_CID_MPEG_VIDC_BASE + 0x31)
enum v4l2_mpeg_vidc_av1_profile {
  V4L2_MPEG_VIDC_AV1_PROFILE_MAIN = 0,
  V4L2_MPEG_VIDC_AV1_PROFILE_HIGH = 1,
  V4L2_MPEG_VIDC_AV1_PROFILE_PROFESSIONAL = 2,
};
#define V4L2_CID_MPEG_VIDC_AV1_LEVEL (V4L2_CID_MPEG_VIDC_BASE + 0x32)
enum v4l2_mpeg_vidc_av1_level {
  V4L2_MPEG_VIDC_AV1_LEVEL_2_0 = 0,
  V4L2_MPEG_VIDC_AV1_LEVEL_2_1 = 1,
  V4L2_MPEG_VIDC_AV1_LEVEL_2_2 = 2,
  V4L2_MPEG_VIDC_AV1_LEVEL_2_3 = 3,
  V4L2_MPEG_VIDC_AV1_LEVEL_3_0 = 4,
  V4L2_MPEG_VIDC_AV1_LEVEL_3_1 = 5,
  V4L2_MPEG_VIDC_AV1_LEVEL_3_2 = 6,
  V4L2_MPEG_VIDC_AV1_LEVEL_3_3 = 7,
  V4L2_MPEG_VIDC_AV1_LEVEL_4_0 = 8,
  V4L2_MPEG_VIDC_AV1_LEVEL_4_1 = 9,
  V4L2_MPEG_VIDC_AV1_LEVEL_4_2 = 10,
  V4L2_MPEG_VIDC_AV1_LEVEL_4_3 = 11,
  V4L2_MPEG_VIDC_AV1_LEVEL_5_0 = 12,
  V4L2_MPEG_VIDC_AV1_LEVEL_5_1 = 13,
  V4L2_MPEG_VIDC_AV1_LEVEL_5_2 = 14,
  V4L2_MPEG_VIDC_AV1_LEVEL_5_3 = 15,
  V4L2_MPEG_VIDC_AV1_LEVEL_6_0 = 16,
  V4L2_MPEG_VIDC_AV1_LEVEL_6_1 = 17,
  V4L2_MPEG_VIDC_AV1_LEVEL_6_2 = 18,
  V4L2_MPEG_VIDC_AV1_LEVEL_6_3 = 19,
  V4L2_MPEG_VIDC_AV1_LEVEL_7_0 = 20,
  V4L2_MPEG_VIDC_AV1_LEVEL_7_1 = 21,
  V4L2_MPEG_VIDC_AV1_LEVEL_7_2 = 22,
  V4L2_MPEG_VIDC_AV1_LEVEL_7_3 = 23,
};
#define V4L2_CID_MPEG_VIDC_AV1_TIER (V4L2_CID_MPEG_VIDC_BASE + 0x33)
enum v4l2_mpeg_vidc_av1_tier {
  V4L2_MPEG_VIDC_AV1_TIER_MAIN = 0,
  V4L2_MPEG_VIDC_AV1_TIER_HIGH = 1,
};
#define V4L2_CID_MPEG_VIDC_TS_REORDER (V4L2_CID_MPEG_VIDC_BASE + 0x34)
#define V4L2_CID_MPEG_VIDC_FILM_GRAIN_PRESENT (V4L2_CID_MPEG_VIDC_BASE + 0x35)
#define V4L2_CID_MPEG_VIDC_METADATA_OUTPUT_TX_FENCE (V4L2_CID_MPEG_VIDC_BASE + 0x38)
#define V4L2_CID_MPEG_VIDC_OUTPUT_TX_FENCE_ID (V4L2_CID_MPEG_VIDC_BASE + 0x39)
#define V4L2_CID_MPEG_VIDC_OUTPUT_TX_FENCE_FD (V4L2_CID_MPEG_VIDC_BASE + 0x3A)
#define V4L2_CID_MPEG_VIDC_METADATA_PICTURE_TYPE (V4L2_CID_MPEG_VIDC_BASE + 0x3B)
#define V4L2_CID_MPEG_VIDC_METADATA_DOLBY_RPU (V4L2_CID_MPEG_VIDC_BASE + 0x40)
#define V4L2_CID_MPEG_VIDC_CLIENT_ID (V4L2_CID_MPEG_VIDC_BASE + 0x41)
#define V4L2_CID_MPEG_VIDC_LAST_FLAG_EVENT_ENABLE (V4L2_CID_MPEG_VIDC_BASE + 0x42)
#define V4L2_CID_MPEG_VIDC_VUI_TIMING_INFO (V4L2_CID_MPEG_VIDC_BASE + 0x43)
#define V4L2_CID_MPEG_VIDC_EARLY_NOTIFY_ENABLE (V4L2_CID_MPEG_VIDC_BASE + 0x44)
#define V4L2_CID_MPEG_VIDC_EARLY_NOTIFY_LINE_COUNT (V4L2_CID_MPEG_VIDC_BASE + 0x45)
#define V4L2_CID_MPEG_VIDC_SIGNAL_COLOR_INFO (V4L2_CID_MPEG_VIDC_BASE + 0x46)
#define V4L2_CID_MPEG_VIDC_CSC (V4L2_CID_MPEG_VIDC_BASE + 0x47)
#define V4L2_CID_MPEG_VIDC_DRIVER_VERSION (V4L2_CID_MPEG_VIDC_BASE + 0x48)
#define V4L2_CID_MPEG_VIDC_GRID_WIDTH (V4L2_CID_MPEG_VIDC_BASE + 0x49)
#define V4L2_CID_MPEG_VIDC_MAX_NUM_REORDER_FRAMES (V4L2_CID_MPEG_VIDC_BASE + 0x4A)
#define V4L2_CID_MPEG_VIDC_INTERLACE (V4L2_CID_MPEG_VIDC_BASE + 0x4B)
#define V4L2_CID_MPEG_VIDC_OPEN_GOP_ENABLE (V4L2_CID_MPEG_VIDC_BASE + 0x4C)
#define V4L2_CID_MPEG_VIDC_METADATA_HDR10_MAX_RGB_INFO (V4L2_CID_MPEG_VIDC_BASE + 0x4D)
#define V4L2_CID_MPEG_VIDC_CAPTURE_DATA_OFFSET (V4L2_CID_MPEG_VIDC_BASE + 0x4E)
#define V4L2_CID_MPEG_VIDC_METADATA_VIEW_ID (V4L2_CID_MPEG_VIDC_BASE + 0x64)
#define V4L2_CID_MPEG_VIDC_METADATA_VIEW_PAIR (V4L2_CID_MPEG_VIDC_BASE + 0x65)
#define V4L2_CID_MPEG_VIDC_METADATA_THREE_DIMENSIONAL_REF_DISP_INFO (V4L2_CID_MPEG_VIDC_BASE + 0x66)
#endif
